-- Q1. What is the total revenue generated by male vs. female customers?

select gender, sum(purchase_amount) as revenue
from customer_shopping_behavior
group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount? 

select customer_id, purchase_amount as spend
from customer_shopping_behavior
where discount_applied = 'yes' and purchase_amount > (select avg(purchase_amount)from customer_shopping_behavior);

-- Q3. Which are the top 5 products with the highest average review rating?

select item_purchased as Products, avg(review_rating) as Average_Review_Rating
from customer_shopping_behavior
group by item_purchased
order by avg (review_rating) desc
limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

select shipping_type, round(avg(purchase_amount),2)
from customer_shopping_behavior
where shipping_type in ('Standard','Express') 
group by shipping_type;

-- Q5. Do suscribed customers spend more? Compare average spend and total revenue between suscribers and non-suscribers

select subscription_status,
count(customer_id) as Total_customers,
round(sum(purchase_amount),2) as Avg_spend,
round(Avg(purchase_amount),2) as Total_Revenue
from customer_shopping_behavior
group by subscription_status
order by Total_revenue, Avg_spend desc;

-- Q6. which 5 products have the highest percentage of purchases with discounts applied?

select item_purchased, round(sum(case when discount_applied = 'yes' then 1 else 0 end)/count(*) * 100,2) as discount_rate
from customer_shopping_behavior
group by item_purchased
order by discount_rate desc
limit 5;

-- Q7. Segment customers into new, returning and loyal based on their total number of previous purchases and
-- show the count of each segment. 

with customer_type as (
select customer_id, Previous_Purchases,
case
when previous_purchases = 1 then 'New'
when previous_purchases between 2 and 10 then 'Returning'
else 'Loyal'
end as customer_segment
from customer_shopping_behavior
)
select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment;


-- Q8. What are the top 3 most purchased products within each category?

with product_counts as (
select category, item_purchased, count(*) as purchase_count
from customer_shopping_behavior
group by category, item_purchased
)
select * 
from (
select category, item_purchased, purchase_count,
row_number() over ( partition by category 
					order by purchase_count desc)
                     as rn 
					from product_counts )
                    as ranked
                    where rn <= 3
                    order by category, rn;

-- Q9. Are Customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status,
count(customer_id) as repeat_buyers
from customer_shopping_behavior
where previous_purchases > 5
group by subscription_status;        

-- Q10. What is the Revenue contribution of each age group?

select age_group, 
       sum(purchase_amount) as Total_Revenue
from customer_shopping_behavior
group by age_group
order by Total_Revenue desc;           
                    



 






